### ISSUE TITLE
Improve Ticket Feature

### ISSUE THREAD

**Issue by JohnnyLeibniz** [ahmadbeirkdar/RUHacks-Bot#1]
- Change naming for ticket channels based on the mentor that creates them - ie _'ticket-1-john'_, _'ticket-5-rachel'_, etc. The numbers are just automatic numbering (ie you don't count based on how many each mentor made. It's just ticket 1, then 2, then 3, etc. The names are just attached for clarity.)

- Add automatic description population based on the content of the ticket. Something like **'Mentor: Andrea | Hackers: Jake & Jess & Joe'**, etc.

- Make sure the archived tickets are only visible by those that were directly a part of the conversation, if possible. IE don't let all mentors see the archived tickets, only those that directly spoke in said ticket.

**Comment by ahmadbeirkdar** [comment]
Commit: 5daffe2fb2d01c02d0141ea33635b945ef039419

All done!
